@startuml
!theme plain

skinparam packageStyle rectangle
skinparam package {
  BackgroundColor White
  BorderColor Black
  BorderThickness 2
  FontSize 12
}

skinparam arrow {
  Color Black
  Thickness 1
}

package "app" <<Package>> {
  
  package "ui" <<Package>> as ui
  package "logic" <<Package>> as logic
  package "data" <<Package>> as data
}

' Dependencies
ui ..> logic : call
logic ..> data : access

@enduml
